CarmineOptions/derisk-research

- web_app/templates/notification.html
1, Asterisk symbol added to mark required fields
2. TG link now opens in a new browser instance
> FE flow improved

- src/helpers.py
Resolves #113 
Modified the portfolio class to add the possibility of adding two instances together.
For this I first added the validation of the second instance being of the same type (portfolio), if not, raise an error.
Then take the tokens values and add them together to return a new portfolio instance containing these new values.
> feat: possibility to sum two portfolios

- notebooks/standardize_events_data.ipynb
> feat: standardize events data

- src/main_chart.py
- src/swap_amm.py
- update_data.py
> Distinguish available liquidity per swap amm

- app.py
due to migration of insfrastructure.
> change API URL for fetching orderbook liquidity

- CONTRIBUTING.md
- PR_RULES.md
Hello
I fixed several spelling issues.
> docs: fix spelling issues

- app.py
- src/chart_utils.py
- src/main_chart.py
hello @djeck1432 please kindly review :)
> feat: harmonize colors

- data_handler/handler_tools/data_parser/serializers.py
- data_handler/handler_tools/data_parser/zklend.py
- data_handler/handlers/loan_states/zklend/events.py
Adding the functionality to standardize. Resolves this #220.
> Standardize event data for accumulators’ data

- data_handler/handler_tools/data_parser/serializers.py
- data_handler/handler_tools/data_parser/zklend.py
- data_handler/handlers/loan_states/zklend/events.py
May fix #240 
- added BorrowingEventData model
- impl parsed event data in `parse_borrowing_event`
> Standardize event data for borrowing event 

- apps/shared/__init__.py
- apps/shared/amms.py
- apps/shared/constants.py
- apps/shared/tests/test_swap_amm.py
Fixes #228 
Continuation of  PR #248 
Fixed merge conflicts
> Rework/test: SwapAmm class

- shared/tests/test _error_handler.py
Create test cases for `error_handle` and also added proper comments for clear
code readability.
> feat: create test cases for error_handler

- apps/shared/tests/test_state_and_loan_entity.py
hello @djeck1432 kindly review #260
> test: add tests for state_and_loan_entity

- apps/shared/tests/test_starknet_client.py
##Description:
###Implemented comprehensive test suite for StarknetClient class covering:
- Basic client initialization
- Contract function calls with retry mechanism
- Token balance queries
- MySwap pool information retrieval
- Error handling and edge cases
##Testing approach:
- Used pytest with async support
- Implemented proper mocking of Starknet network calls
- Added both positive and negative test scenarios
##Test commands:
bash:
```
pip install pytest-asyncio
pytest apps/shared/tests/test_starknet_client.py -v
```
Note: All test cases passed as expected
> feat: Add test cases for starknet_client

- apps/data_handler/handler_tools/data_parser/nostra.py
- apps/data_handler/handler_tools/data_parser/serializers.py
- apps/data_handler/handlers/loan_states/nostra_alpha/events.py
> Added data serializer for process_debt_mint_event and process_debt_burn_event functions

- apps/data_handler/celery_app/celery_conf.py
- apps/data_handler/celery_app/event_tasks.py
> Tasks for processing and storing ZkLend protocol events

- apps/data_handler/handler_tools/data_parser/nostra.py
- apps/data_handler/handler_tools/data_parser/serializers.py
- apps/data_handler/handlers/loan_states/nostra_alpha/events.py
Add standardized event data for Nostra Alpha
Issue #284 closes
> added interest_rate_model anddebt_transfer serializers

- apps/data_handler/handler_tools/data_parser/nostra.py
- apps/data_handler/handler_tools/data_parser/serializers.py
- apps/data_handler/handlers/loan_states/nostra_alpha/events.py
BearingCollateralMintEventData + BearingCollateralBurnEventData serialiser and usage
- added BearingCollateralMintEventData and BearingCollateralBurnEventData serialiser
- added creation of parsers to NostraDataParser
- replaced code in process_interest_bearing_collateral_mint_event
This PR fixes https://github.com/CarmineOptions/derisk-research/issues/286
> Feature standarize mint and burn

- apps/data_handler/handler_tools/data_parser/nostra.py
- apps/data_handler/handler_tools/data_parser/serializers.py
- apps/data_handler/handler_tools/data_parser/serializers/__init__.py
- apps/data_handler/handler_tools/data_parser/serializers/nostra.py
- apps/data_handler/handlers/loan_states/nostra_alpha/events.py
> feat: standarize event data for mint and burn none-interest

- .github/workflows/ci.yml
- .github/workflows/pylint.yml
> fix pipeline

- apps/data_handler/tests/liquidation_test.py
> feat: create test cases for BaseDBLiquidableDebtDataHandler

- apps/dashboard_app/helpers/loans_table.py
- apps/dashboard_app/tests/test_state.py
- apps/data_handler/handlers/loan_states/hashtack_v0/events.py
- apps/data_handler/handlers/loan_states/hashtack_v1/events.py
- apps/data_handler/handlers/loan_states/nostra_mainnet/events.py
- apps/data_handler/handlers/loan_states/zklend/events.py
- apps/data_handler/tests/health_ratio_test/test_health_ratio_tests.py
- apps/shared/state.py
- apps/web_app/utils/zklend.py
> feat: create new interface for get_protocols

- README.md
- apps/dashboard_app/README.md
- apps/data_handler/README.md
- apps/web_app/README.md
closes #337 
- update the main [README.md](https://github.com/CarmineOptions/derisk-research/blob/master/README.md) file at the root of the project
- I noticed that some directory don't a readme file but i still referenced them
- [shared](https://github.com/CarmineOptions/derisk-research/tree/master/apps/shared)
- [dashboard_app](https://github.com/CarmineOptions/derisk-research/tree/master/apps/dashboard_app)
> docs: update documentation for all apps

- apps/data_handler/tests/order_book/test_myswap.py
> feat/test_myswap 

- apps/sdk/Dockerfile
- apps/sdk/README.md
- apps/sdk/docker-compose.yaml
> feat: configure docker for sdk project

- .gitignore
- apps/data_handler/tests/order_book/test_uniswap.py
> Add test cases for Uniswap2 order book

- apps/data_handler/tests/order_book/test_ekubo.py
🔍 Implemented comprehensive unit tests for the EkuboOrderBook class to ensure robust functionality and edge case handling.
- Closes #371 
- Added detailed test coverage for order book initialization 📊
- Implemented tests for price and liquidity fetching 💹
- Created parametrized tests for tick calculations 🧮
- Added edge case and empty data scenario tests 🛡️
**Images of what has been modified:**
- Verified price and liquidity data processing ✅
- Tested square root ratio calculations 📐
- Confirmed proper asks and bids sorting 🔀
- Handled various tick scenarios 🎯
- Used `pytest` for test framework 🐍
- Implemented mocking for API connections 🎭
- Added type and value assertions for data integrity 🛠️
**The test running properly:**
Ready for review and merge! 🌟
> feat: add test cases for ekubo order book

- apps/dashboard_app/charts/utils.py
- apps/dashboard_app/helpers/protocol_stats.py
- apps/dashboard_app/helpers/tools.py
- apps/data_handler/handlers/loan_states/zklend/events.py
- apps/shared/amms.py
- apps/shared/loan_entity.py
@djeck1432
Closes #396 
* [`apps/dashboard_app/charts/utils.py`](diffhunk://#diff-760a89c80fe4a341571f6b47c2ce8faf079af5a6ecd3a091ef0b34393f59f785R5-L15): Introduced asynchronous operations for fetching AMM balances and updated the retrieval of current prices. [[1]](diffhunk://#diff-760a89c80fe4a341571f6b47c2ce8faf079af5a6ecd3a091ef0b34393f59f785R5-L15) [[2]](diffhunk://#diff-760a89c80fe4a341571f6b47c2ce8faf079af5a6ecd3a091ef0b34393f59f785L177-R185) [[3]](diffhunk://#diff-760a89c80fe4a341571f6b47c2ce8faf079af5a6ecd3a091ef0b34393f59f785L187-R195)
* [`apps/data_handler/handlers/loan_states/zklend/events.py`](diffhunk://#diff-40dab22f26f423d6c54d61b098d3d854afcf459a617f5c205a75f6c7b566620cL161-R165): Modified debt liquidation calculations to use `Decimal` for more precise handling of …
> Fixing errors in loan data handling and passing prices as a parameter

- apps/data_handler/tests/order_book/test_haiko.py
Added test cases for `HaikoOrderBook`
> add test cases for haiko order

- apps/sdk/api/user.py
- apps/sdk/schemas/schemas.py
Created  new `user_deposit` endpoint
resolves #405
> feat: get_user_deposit enpoint

- apps/sdk/alembic.ini
- apps/sdk/alembic/README
- apps/sdk/alembic/env.py
- apps/sdk/alembic/script.py.mako
> Supa mega/issue402

- .gitignore
- apps/sdk/README.md
- apps/sdk/api/user.py
- apps/sdk/db_connector.py
- apps/sdk/poetry.lock
- apps/sdk/pyproject.toml
- apps/sdk/pytest.ini
- apps/sdk/schemas/schemas.py
- apps/sdk/tests/conftest.py
- apps/sdk/tests/test_db_connector.py
- apps/sdk/tests/test_loan_state.py
Refactor: update SDK project dependencies and configurations
- Adjust import statements and test cases
- Update database connector and schemas
- Improve type hints and error handling
- Add psycopg2-binary to project dependencies
- Update .gitignore to include .venv
- Modify README.md docker-compose command
> [SDK] Fix refactory imports and tests

- apps/dashboard_app/charts/constants.py
- apps/dashboard_app/charts/main.py
- apps/dashboard_app/charts/main_chart_figure.py
- apps/dashboard_app/charts/utils.py
1. Reworked `Detail of a loan` chart 
2. Calculated data for `detail loan`
3. Inserted into main chart class
> Add detail of a loan

- apps/sdk/api/user.py
- apps/sdk/tests/test_user_debt.py
> test: test user debt

- apps/dashboard_app/.env.dev
- apps/dashboard_app/tests/test_tools.py
> [Margin app] Add test cases for tools functions

- devops/dev/docker-compose.data-handler.yaml
> fix: Celery tasks in Dev Data Handler

- apps/dashboard_app/helpers/ekubo.py
- apps/dashboard_app/tests/test_ekubo.py
Closes #440
- I created tests for the `ekubo.py` file
- Modified the ekubo `fetch_liquidity()` function to prevent infinite recursion
> [Dashboard] Add test cases for Ekubo

- apps/data_handler/handler_tools/constants.py
- apps/data_handler/handler_tools/data_parser/nostra.py
- apps/data_handler/handler_tools/nostra_mainnet_settings.py
- apps/data_handler/handlers/loan_states/nostra_mainnet/events.py
- apps/data_handler/handlers/loan_states/nostra_mainnet/run.py
- apps/shared/starknet_client.py
Closes #439 
* Added new protocol addresses to `ProtocolAddresses` class in `constants.py` to support additional contracts. [[1]](diffhunk://#diff-40b8c401b0827b23ef50b1165221466d079008e48fd88dc34d87f062491587e0L24-R27) [[2]](diffhunk://#diff-40b8c401b0827b23ef50b1165221466d079008e48fd88dc34d87f062491587e0R59-R62) [[3]](diffhunk://#diff-40b8c401b0827b23ef50b1165221466d079008e48fd88dc34d87f062491587e0R72-R74) [[4]](diffhunk://#diff-40b8c401b0827b23ef50b1165221466d079008e48fd88dc34d87f062491587e0R84-R86) [[5]](diffhunk://#diff-40b8c401b0827b23ef50b1165221466d079008e48fd88dc34d87f062491587e0R96-R108) [[6]](diffhunk://#diff-40b8c401b0827b23ef50b1165221466d079008e48fd88dc34d87f062491587e0R139-R166)
* Updated `NOSTRA_EVENTS_MAPPING` and `NOSTRA_MAINNET_EVENTS_TO_METHODS` to improve readability …
> Refactor NostraDataParser methods to class methods and update StarknetClient to use FullNodeClient

- apps/dashboard_app/charts/main.py
This PR introduces a new method called displayBox, which enhances the visibility of transaction types by color-coding them:
Debit is displayed in red
Collateral is displayed in green
Deposit is displayed in red
>  displayBox Method for Improved Transaction Visualization

- apps/dashboard_app/app/crud/base.py
closes #499 
- Added new `DBConnectorAsync` class that implements all specified methods into `base.py`. Also used [this](https://github.com/djeck1432/spotnet/blob/main/margin_app/app/crud/base.py#L20) as a reference.
> feat [Dashboard App] Add an async database connector for CRUD operations

- apps/dashboard_app/data_conector.py
feat [[Dashboard app] Create DataConnectorAsync #510](https://github.com/CarmineOptions/derisk-research/issues/510)
Does it look like the expected result, or do I need to add something like asyncpg?
Request review:
@djeck1432
> add DataConnectorAsync

- README.md
- apps/frontend_dashboard/.dockerignore
- apps/frontend_dashboard/Dockerfile
- apps/frontend_dashboard/package.json
This PR adds a `Dockerfile` and updates the `README.md` to containerize the frontend project located in `/apps/frontend_dashboard.` The Docker setup allows the project to run consistently across different environments, making it easier to develop, test, and deploy.
- **Added Dockerfile:**
- Created a `Dockerfile` to containerize the frontend project.
- Used **node:20-alpine** as the base image for a lightweight and efficient setup.
- Copied necessary files (`package.json`, `package-lock.json`, `tsconfig.json`, `tsconfig.node.json`, `tsconfig.app.json`) and installed dependencies.
- Exposed port `5173` (default for Vite) and set the `npm run dev` command as the entry point.
```Dockerfile
FROM node:20-alpine
WORKDIR /app
COPY package*.json .
COPY tsconfig.json .
COPY tsconfig.node.json . …
```
> Dockerize Frontend Dashboard

- apps/shared/db/base.py
> created async InitializerDBConnector

- apps/dashboard_app/app/models/base.py
- apps/dashboard_app/app/tests/test_watcher_mixin.py
- apps/dashboard_app/app/utils/watcher_mixin.py
- apps/dashboard_app/tests/test_watcher_mixin.py
Closes #501 
- Added missing dependencies in `base.py`
- Created `WatcherMixin` class and moved next functions into it:
- _exists_in_db
- health_ratio_is_valid
- validate_health_ratio
- validate_fields
- Added some tests for `WatcherMixin` class
> feat [Dashboard App]: Add WatcherMixin

- apps/frontend_dashboard/package-lock.json
- apps/frontend_dashboard/package.json
- apps/frontend_dashboard/src/components/Counter.test.tsx
- apps/frontend_dashboard/src/components/Counter.tsx
- apps/frontend_dashboard/src/test/setup.ts
- apps/frontend_dashboard/vitest.config.ts
**### Add Vitest Testing Setup**
Changes :
1. Installed Vitest and testing libraries (vitest, @testing-library/react, jest-dom)
2. Added Vitest configuration for React/TypeScript
3. Created  Counter component with tests showing:
Example Component and Tests
Added example component with co-located test:
- src/components/Counter.tsx: Simple counter component
- src/components/Counter.test.tsx: Example tests demonstrating:
- Basic component rendering
- DOM element presence verification
- User interaction testing (button clicks)
State change verification
4. Added npm scripts:
"test": "vitest",
"test:ui": "vitest --ui",
"test:coverage": "vitest run --coverage"
5
. Testing: 
npm test           # Run tests
npm run test:ui    # Run with UI
npm run test:coverage  # Get coverage
> feat : Install Vitest 

- apps/dashboard_app/entrypoint.sh
> changed dashboard_app/entrypoint.sh to handle restarting of docker

- apps/dashboard_app/app/tests/test_subscription.py
- apps/dashboard_app/tests/protocol_stats_test.py
- apps/dashboard_app/tests/test_dashboard_data_handler.py
- apps/dashboard_app/tests/test_ekubo.py
- apps/dashboard_app/tests/test_loans_table.py
- apps/dashboard_app/tests/test_state.py
- apps/dashboard_app/tests/test_tools.py
- apps/dashboard_app/tests/test_utils.py
- apps/dashboard_app/tests/test_watcher_mixin.py
> added skip on imort module fail

- apps/dashboard_app/helpers/load_data.py
- apps/dashboard_app/tests/test_dashboard_data_handler.py
Closes #538 
- Attempted to change sync methods usage to async
> feat [Dashboard App]: Rework calling sync methods to async

- apps/dashboard_app/app.Dockerfile
- apps/dashboard_app/app/api/watcher.py
- apps/dashboard_app/app/services/fetch_data.py
- devops/dev/docker-compose.dashboard-app.yaml
(https://github.com/CarmineOptions/derisk-research/issues/559)[https://github.com/CarmineOptions/derisk-research/issues/559]
draft
> fix docker?

- apps/data_handler/handlers/loan_states/vesu/events.py
- apps/data_handler/models/base.py
> implemented save vesu data into db

- apps/dashboard_app/app/models/base.py
- apps/dashboard_app/app/models/watcher.py
> Add tablename generation

- apps/frontend_dashboard/src/routes/Dashboard.jsx
This PR implements localStorage caching for the dashboard trade history, addressing issue #606:
Per-wallet caching: Trade history is cached in localStorage using a unique key for each wallet address.
Instant load: On page load or wallet change, cached history (if available) is displayed immediately for a fast user experience.
Background refresh: The latest history is always fetched from the API in the background and both the UI and cache are updated.
Wallet switching: When the user switches wallets, the correct cached history is shown and refreshed.
Cache clearing: On wallet disconnect, the cache for that wallet is cleared.
Improved UX: Users no longer experience slow history loading after the first fetch for each wallet.
This change significantly improves perceived performance and …
> feat(dashboard): cache trade history in localStorage per wallet for instant load and background refresh (closes #606)

- apps/dashboard_app/.env.dev
- apps/dashboard_app/app/core/config.py
- apps/dashboard_app/entrypoint.sh
- apps/data_handler/.env.dev
- apps/data_handler/.env.example
- apps/data_handler/init-db/init.sql
- devops/dev/docker-compose.dashboard-app.yaml
- devops/dev/docker-compose.data-handler.yaml
- devops/dev/docker-compose.db.yaml
Close https://github.com/CarmineOptions/derisk-research/issues/633
> Merge envs. Fix docker copose files 

- apps/dashboard_app/app/api/watcher.py
- apps/dashboard_app/app/utils/fucntools.py
- apps/dashboard_app/app/utils/values.py
- apps/data_handler/db/models/__init__.py
- apps/data_handler/db/models/liquidable_debt.py
- apps/data_handler/handlers/health_ratio_level/nostra_alpha.py
- apps/data_handler/handlers/health_ratio_level/nostra_mainnet.py
- apps/data_handler/handlers/health_ratio_level/zklend.py
- apps/data_handler/handlers/loan_states/vesu/events.py
- apps/data_handler/main.py
- apps/data_handler/tests/loan_state/vesu/test_events.py
- apps/shared/db/models/__init__.py
- apps/shared/db/models/health_ratio.py
- apps/shared/tests/test_swap_amm.py
> move health ratio data fetching from data handler to dashboard

- .gitignore
- apps/dashboard_app/helpers/settings.py
- apps/shared/constants.py
Update token address accordingly to new one. Address source: https://starkscan.co/token/0x57912720381af14b0e5c87aa4718ed5e527eab60b3801ebf702ab09139e38b
> Fix token address for wstETH
